apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-galera
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - mariadb.yaml
  - users
  - phsysical-backup.yaml
  - phsysical-backup-entenhausen.yaml
  - databases
  - grants
  - passwords
  - maxscale.yaml

secretGenerator:
  - name: mariadb
    envs:
      - mariadb-root.env
