apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: mariadb-galera-backup
  namespace: mariadb-galera
spec:
  mariaDbRef:
    name: mariadb-galera
  schedule:
    cron: "0 */6 * * *"
    suspend: false
    immediate: true
  maxRetention: 720h # 30 days
  compression: bzip2
  storage:
    s3:
      bucket: mariadb-galera-backup
      prefix: feather-core-backups
      endpoint: s3.onelitefeather.net
      tls:
        enabled: true
      accessKeyIdSecretKeyRef:
        name: mariadb
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb
        key: secret-access-key
  # Define a PVC to use as staging area for keeping the backups while they are being processed.
  stagingStorage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 50Gi
      accessModes:
        - ReadWriteOnce
  timeout: 1h
  #  podAffinity: true
  #  serviceAccountName: backup
  resources:
    requests:
      cpu: 2
      memory: 256Mi
    limits:
      cpu: 2
      memory: 512Mi