apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otis
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/otis/
patches:
  - path: release.yaml

secretGenerator:
  - name: harbor-pull
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=harbor.onelitefeather.dev.dockerconfigjson.sops.json
  - name: otis-app-db
    envs:
      - otis.sops.env