apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependency-track
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/dependency-track
patches:
  - path: release.yaml

secretGenerator:
  - name: dependency-track-env
    envs:
      - dtrack.env
