apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: s3-store
spec:
  configuration:
    destinationPath: s3://feather-core-cluster-pg-backup/backups
    # MariaDB uses endpoint without scheme; CNPG expects full URL
    endpointURL: https://s3.onelitefeather.net
    s3Credentials:
      accessKeyId:
        name: cnpg-backup
        key: access-key-id
      secretAccessKey:
        name: cnpg-backup
        key: secret-access-key
    wal:
      compression: gzip