apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-galera
generatorOptions:
  disableNameSuffixHash: true
resources: []

secretGenerator:
  - name: user-plotsquared-secret
    envs:
      - plotsquared.sops.env
  - name: user-discordbot-secret
    envs:
      - discordbot.sops.env
  - name: uptime-kuma-secret
    envs:
      - uptime-kuma.sops.env
  - name: user-leantime-secret
    envs:
      - leantime.sops.env