apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: leantime
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/leantime/
patches:
  - path: release.yaml

secretGenerator:
  - name: leantime-env
    files:
      - leantime.sops.env
  - name: cf-origin-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=cf-origin-tls.sops.crt
      - tls.key=cf-origin-tls.sops.key