apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../../../apps/base/outline/
patches:
  - path: release.yaml

secretGenerator:
  - name: outline-env
    files:
      - .env=outline.sops.env
  - name: cf-origin-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=cf-origin-tls.sops.crt
      - tls.key=cf-origin-tls.sops.key